all:
	x64sc -autostartprgmode 1 -autostartprgdiskimage "/Users/cirelli/Projects/Steve/adventofcode.com/2021/day/2/6502/.cache/pilot_p2.prg" -verbose -autostart "/Users/cirelli/Projects/Steve/adventofcode.com/2021/day/2/6502/.cache/pilot_p2.prg"
